### ISSUE TITLE
Menu scene - 

### ISSUE THREAD

**Issue by Scarabian** [Scarabian/UniJammers-GDTVJam2023#22]
Main menu 
Options Menu
Pause Menu

*******************************Wish list****************************

**Comment by jomarcenter-mjm** [comment]
Working on it

**Comment by Ste-Gar** [comment]
We can go about this two ways:
- do this from the ground up, as @jomarcenter-mjm has already started.
The current PR has a start menu and code for a resolution selection dropdown; there is no option menu UI yet. I'd like to have at least that before merging, and possibly volume settings (at least a general sound volume bar).

- use the package I shared a few days ago; I think the only thing missing in there is the pause menu, but it also already implements scene management and sound settings.

@Scarabian @jomarcenter-mjm let me know what you think.

**Comment by jomarcenter-mjm** [comment]
I think using the package is better (as long as its free to use and everyone can access it)

**Comment by Ste-Gar** [comment]
Menu scene and pause menu have been merged.

To load the correct scene when starting from the game menu, the Menu component in the TitleScreen object will need to be updated with the proper scene name.

The pause screen can be added to any scene by adding PauseCanvas prefab (it is in \prefabs\UI). It should automatically work without further setup. The input for the pause screen are currently ESC and P; these can be changed in the input actions.
